### ISSUE TITLE
User can't move past password entry

### ISSUE THREAD

**Issue by bobcathost** [benchmarkstudios/wc-category-locker#1]
Assigned Products to pw protected category.  They are successfully removed from the normal product feed.  When navigating to the category page, it prompts for password, but after a successful, or unsuccessful password entry the page just reloads with the password prompt box is still there.

**Comment by bobcathost** [comment]
http://www.printmy.biz/product-category/chucknash/

**Comment by lukasjuhas** [comment]
Hi @bobcathost,

We've have left this out as default Wordpress password locked posts doesn't have any (success or error) messages either which is probably not very user friendly.. I'll look in to this and see what we can do.

Thanks!

**Comment by bobcathost** [comment]
Thanks for quick response.  So what is happening, and how does my client view his “pw protected” category?

**Comment by lukasjuhas** [comment]
Hi @bobcathost,

Sorry, I edited my previous message... here it is:

Are you using some kind of cache plugin?

Also check if you are using correct password that you set for category. There are currently no success or error messages when entering password to match the same behaviour like WP pages have.

**Comment by bobcathost** [comment]
Actually I am! -à Wordfence Security

**Comment by lukasjuhas** [comment]
It might worth trying to disable it just for a minute and try it again. Usually the best way how to test the plugin would be disabling all other plugins and see if problem persist.

Let me know how did that go.
