### ISSUE TITLE
plugin doesn't recognize passwords with new WC

### ISSUE THREAD

**Issue by japandler** [benchmarkstudios/wc-category-locker#3]
Issue:
resets to password page despite proper login attempt. 

WooCommerce Ver: 3.2.3
WordPress Ver: 4.8.3

Recreation steps:
Create Product Category
Create Custom Permalink in Category
Create Category Password
Setup Products in Category
Go to category login page
Type in correct password

Will receive same page. 
There are no errors on the page when this occurs. 

Workaround: I've found that if you attempt to login on the http version of the page, it will fail, but then you'll have access to the https version of it, and vice versa. Gaining access on one version will not allow access on the other. 

This was working until the recent update to WooCommerce.

**Comment by lukasjuhas** [comment]
Hey, thanks for getting in touch and letting us know! Will look into this.

Lukas

**Comment by lukasjuhas** [comment]
Hey @japandler, I have just done some testing, I cannot reproduce your problem. I'm wondering if you are using some kind of cache plugin, or caching on your server? 

Please double check your passport and try the process in different browser / incognito mode to see if it's still happening.

I have tested it on bare setup of woocommerce, storefront theme with some test products and categories and everything works well.

I hope that heps, thanks!

Lukas
