### ISSUE TITLE
 add_action priority

### ISSUE THREAD

**Issue by marcs84** [benchmarkstudios/wc-category-locker#4]
I noticed that in order to make the plugin work in some themes it is necessary to lower the priority level to the add_action function in the wc-category-locker/frontend.php file on lines 12 and 13 to the default value 10. 
It is advisable to set it to the current values ​​of 25 and 26, instead of lowering it?

This rows:
add_action('pre_get_posts', [$this, 'password'], 25);
add_action('pre_get_posts', [$this, 'update_shop_queries'], 26);

Change in:
add_action('pre_get_posts', [$this, 'password']);
add_action('pre_get_posts', [$this, 'update_shop_queries']);

Thank you
Marco

**Comment by lukasjuhas** [comment]
Hi @marcs84, thanks for your message, you are absolutely right. I will add these in the next release shortly.
